server:
  port: 8762

spring:
  application:
    name: eureka2

eureka:
  instance:
    hostname: node2
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node3:8763/eureka/
  server:
    #关闭自我保护模式（缺省为打开）
    enable-self-preservation:false
spring.cloud.config.discovery.enabled: true